# Analysing data about countries

Brute force search for all correlations. A $R^2$ value larger than $0.9$ is
required.
```{r, label=data}
df = read.csv('factbook.csv', header=T, dec=".", na.strings="")
for (colx in names(df)) {
    if (colx == "Country") next
    for (coly in names(df)) {
        if (coly == "Country" || colx == coly) next
        tmp = data.frame(x=df[colx], y=df[coly])
        reg = lm(data=tmp)
        sum = summary(reg)
        if (sum$r.squared > 0.9) { print(colx); print(coly); print(sum$r.squared) }
    }
}
```

Plot some interesting (i.e. surprising) ones.
```{r, label=plot}
ggplot(data=df, aes(x=Internet.users, y=Oil...consumption.bbl.day.)) + scale_x_log10() + scale_y_log10() + geom_point() + geom_smooth(method='lm')
ggplot(data=df, aes(x=Internet.hosts, y=Military.expenditures...dollar.figure)) + scale_x_log10() + scale_y_log10() + geom_point() + geom_smooth(method='lm')
```


## Clustering

First, select some columns and remove `NA` values.
```{r, label=clean}
df_clus_raw = df[
    !is.na(df$Public.debt...of.GDP.) &
    !is.na(df$GDP),
]
df_clus = data.frame(
    df_clus_raw$Public.debt...of.GDP.,
    df_clus_raw$GDP
)
# Check that not all countries are removed.
str(df_clus)
```

Try a clustering. Not really interesting.
```{r, label=clustering}
kmeans = kmeans(df_clus, 8)
ggplot(data=df_clus, aes(x=df_clus_raw.Public.debt...of.GDP., y=df_clus_raw.GDP, color=factor(kmeans$cluster))) + scale_y_log10() + geom_point()
```
